---
- name: Install Rust components
  ansible.builtin.command: rustup-init -y
  changed_when: false

- name: Rustfmt settings
  block:
    - name: Create config directories
      ansible.builtin.file:
        path: /home/{{ ansible_user }}/{{ item }}
        state: directory
        mode: "0700"
      loop:
        - .config
        - .config/rustfmt
    - name: Copy rustfmt.toml
      ansible.builtin.copy:
        src: rustfmt.toml
        dest: /home/{{ ansible_user }}/.config/rustfmt/rustfmt.toml
        mode: "0600"
