---
- name: Install Rust components
  ansible.builtin.command: rustup-init -y --no-modify-path
  changed_when: false

- name: Rustfmt settings
  block:
    - name: Create config directories
      ansible.builtin.file:
        path: "{{ ansible_facts['user_dir'] }}/{{ item }}"
        state: directory
        mode: "0700"
      loop:
        - .config
        - .config/rustfmt
    - name: Copy rustfmt.toml
      ansible.builtin.copy:
        src: rustfmt.toml
        dest: "{{ ansible_facts['user_dir'] }}/.config/rustfmt/rustfmt.toml"
        mode: "0600"
