- name: Get Current Paths
  block:
    - name: Get Current Dir Path
      ansible.builtin.command: pwd
      register: updater_wsl_dotfiles_dir
      changed_when: false
    - name: Get Ansible Path
      ansible.builtin.command: which ansible-playbook
      register: updater_wsl_ansible_path
      changed_when: false

- name: Setup Updater Service
  become: true
  block:
    - name: Install jq
      ansible.builtin.apt:
        name: jq
        state: present
    - name: Copy Updater Service Template
      ansible.builtin.template:
        src: updater.service.j2
        dest: /etc/systemd/system/updater.service
        mode: "0644"
    - name: Enable Updater Service
      ansible.builtin.systemd:
        name: updater.service
        enabled: true
        daemon_reload: true
        state: restarted
