- name: Set rc File System to be Mounted on Startup
  become: true
  ansible.builtin.lineinfile:
    path: /etc/fstab
    regexp: ^none
    line: 'none none rc defaults 0 0'
    mode: '0644'

- name: Get Current Dir Path
  ansible.builtin.command: pwd
  register: dotfiles_dir
  changed_when: false
- name: Get Ansible Path
  ansible.builtin.command: which ansible-playbook
  register: ansible_path
  changed_when: false
- name: Copy mount.rc
  become: true
  ansible.builtin.template:
    src: mount.rc.j2
    dest: /sbin/mount.rc
    mode: '0755'
