---
- name: Run Playbook for MacOS Env
  hosts: local
  connection: local
  roles:
    - role: check_os
      check_os_expected_family: Darwin
    - brew
    - mac
    - rc
    - go
    - rust
    - python
    - mise
    - docker
    - k8s
    - git
    - workspace
