- name: Run Playbook for Local WSL Env (pixiv)
  hosts: local
  connection: local
  roles:
    - apt
    - brew
    - rc
    - pixiv
    - pip
    - go
    - docker
    - role: gpg
      vars:
        gpg_pinentry_program: "/mnt/c/Program Files (x86)/Gpg4win/bin/pinentry.exe"
    - git_pixiv
    - updater_pixiv
