---
- name: Run Playbook for sdplane Dev Environment
  hosts: local
  connection: local
  roles:
    - role: check_os
      check_os_expected_system: Linux
    - apt
    - sdplane
    - brew
    - rc
    - go
    - rust
    - python
    - mise
    - youki
    - docker
    - role: git
      git_go_credentials_enabled: false
    - completion
