---
- name: Run Playbook for sdplane Dev Environment
  hosts: local
  connection: local
  roles:
    - role: check_os
      check_os_expected_system: Linux
    - apt
    - sdplane
    - brew
    - rc
    - llm
    - go
    - rust
    - python
    - mise
    - youki
    - docker
    - k8s
    - role: git
      git_sdplane: true
    - workspace_sdplane
    - completion
