- name: Run Playbook for Server
  hosts: local
  connection: local
  roles:
    - apt
    - server
    - brew
    - rc
    - pip
    - go
    - mise
    - container
    - k8s
    - db
    - git
    - workspace
