- name: Run Playbook for Server on localhost
  hosts: local
  connection: local
  roles:
    - brew
    - rc
    - pip
    - asdf
    - go
    - docker
    - role: gpg
      vars:
        pinentry_program: /usr/bin/pinentry-curses
    - git
