---
- name: Run Playbook for Server
  hosts: local
  connection: local
  roles:
    - role: check_os
      check_os_expected_system: Linux
    - apt
    - server
    - brew
    - rc
    - go
    - rust
    - python
    - mise
    - youki
    - docker
    - k8s
    - git
    - workspace
