- name: Run Playbook for Server
  hosts: local
  connection: local
  roles:
    - apt
    - brew
    - rc
    - pip
    - asdf
    - go
    - docker
    - db
    - role: gpg
      vars:
        pinentry_program:
    - git
    - updater-server
