- name: Run Playbook for Server
  hosts: local
  connection: local
  roles:
    - apt
    - brew
    - rc
    - pip
    - go
    - docker
    - k8s
    - db
    - role: gpg
      vars:
        gpg_pinentry_program:
    - git
    - updater_server
