- name: Run Playbook for Server
  hosts: local
  connection: local
  roles:
    - brew
    - rc
    - pip
    - asdf
    - go
    - docker
    - role: gpg
      vars:
        pinentry_program: /usr/bin/pinentry-curses
    - role: git
      vars:
        prj_dir: ~/Documents/prj
