---
- name: Run Playbook for Local WSL Env
  hosts: local
  connection: local
  roles:
    - role: check_os
      check_os_expected_system: Linux
    - apt
    - wsl
    - brew
    - role: rc
      rc_browser_path: "/usr/bin/chrome"
    - go
    - rust
    - python
    - mise
    - youki
    - docker
    - k8s
    - git
    - workspace
