- name: Run Playbook for Local WSL Env
  hosts: local
  connection: local
  roles:
    - apt
    - wsl
    - brew
    - rc
    - pip
    - go
    - rust
    - mise
    - youki
    - docker
    - k8s
    - db
    - git
    - workspace
