---
- name: Run Playbook for Local WSL Env
  hosts: local
  connection: local
  roles:
    - role: check_os
      check_os_expected_family: Debian
    - apt
    - wsl
    - brew
    - rc
    - go
    - rust
    - python
    - mise
    - youki
    - docker
    - k8s
    - git
    - workspace
