- name: Run Playbook for Local WSL Env
  hosts: local
  connection: local
  roles:
    - apt
    - wsl
    - brew
    - rc
    - pip
    - mise
    - go
    - docker
    - db
    - role: gpg
      vars:
        gpg_pinentry_program: /usr/bin/pinentry-curses
    - git
    - updater_wsl
