- name: Run Playbook for Local WSL Env
  hosts: local
  connection: local
  roles:
    - wsl
    - brew
    - rc
    - pip
    - asdf
    - go
    - docker
    - role: gpg
      vars:
        pinentry_program: '/mnt/c/Program Files (x86)/Gpg4win/bin/pinentry.exe'
    - role: git
      vars:
        prj_dir: ~/prj
