- name: Get Current Dir Path
  ansible.builtin.command: pwd
  register: dotfiles_dir
  changed_when: false
- name: Get ansible-playbook Path
  ansible.builtin.command: which ansible-playbook
  register: ansible_playbook_path
  changed_when: false
- name: Setup Updater for Server
  ansible.builtin.cron:
    name: update packages
    minute: 0
    hour: 4
    job: '{{ ansible_playbook_path.stdout }} -v -u {{ ansible_user }} -i {{ dotfiles_dir.stdout }}/inventory {{ dotfiles_dir.stdout }}/server-update.yaml'

- name: Get reboot Path
  ansible.builtin.command: which reboot
  register: reboot_path
  changed_when: false
- name: Setup Periodical reboot for Server
  become: true
  ansible.builtin.cron:
    name: reboot server
    minute: 30
    hour: 4
    user: root
    job: '{{ reboot_path.stdout }} 0'
