- name: Install pip Packages
  ansible.builtin.pip: # noqa: package-latest
    executable: /home/linuxbrew/.linuxbrew/bin/pip3
    state: latest
    name:
      - pip
      - ansible
      - ansible-lint
      - black
      - flake8
      - mypy
