- name: Install packaging Package
  ansible.builtin.command: /home/linuxbrew/.linuxbrew/bin/pip3 install --break-system-packages packaging
  changed_when: false

- name: Install pip Packages
  ansible.builtin.pip: # noqa: package-latest
    executable: /home/linuxbrew/.linuxbrew/bin/pip3
    extra_args: --break-system-packages
    state: latest
    name:
      - pip
      - ansible
      - ansible-lint
      - black
      - flake8
      - mypy
      - pydot
      - pipenv
