---
- name: Update Homebrew-related components
  block:
    - name: Update Homebrew & Homebrew packages
      community.general.homebrew:
        update_homebrew: true
        upgrade_all: true
    - name: Cleanup
      ansible.builtin.shell: |
        {{ check_os_brew_base_path }}/bin/brew autoremove
        {{ check_os_brew_base_path }}/bin/brew cleanup
      changed_when: false
    - name: Update Homebrew cask applications
      community.general.homebrew_cask:
        upgrade_all: true
      when: ansible_facts["system"] == "Darwin"

- name: Update Go packages
  ansible.builtin.shell: |
    export PATH=$PATH:/usr/local/go/bin
    {{ ansible_facts['user_dir'] }}/go/bin/gup update
  changed_when: false

- name: Update Rust
  ansible.builtin.command: "{{ check_os_brew_base_path }}/bin/rustup update"
  changed_when: false

- name: Update Krew packages
  ansible.builtin.command: "{{ check_os_brew_base_path }}/bin/kubectl-krew upgrade"
  changed_when: false

- name: Update Python packages
  ansible.builtin.command: "{{ check_os_brew_base_path }}/bin/uv tool upgrade --all"
  changed_when: false

- name: Update mise packages
  ansible.builtin.command: "{{ check_os_brew_base_path }}/bin/mise upgrade --bump"
  changed_when: false

- name: Prune Docker components
  ansible.builtin.shell: |
    {{ check_os_brew_base_path }}/bin/docker image prune -a -f
    {{ check_os_brew_base_path }}/bin/docker volume prune -a -f
    {{ check_os_brew_base_path }}/bin/docker network prune -f
  changed_when: false
