---
- name: Update Homebrew-related components
  block:
    - name: Update Homebrew & Homebrew packages
      community.general.homebrew:
        update_homebrew: true
        upgrade_all: true
    - name: Prune Homebrew cache
      ansible.builtin.shell: |
        set -e
        brew autoremove
        brew cleanup
      changed_when: false
    - name: Update Homebrew cask applications
      community.general.homebrew_cask:
        upgrade_all: true
      when: ansible_facts.system == "Darwin"

- name: Update Go packages
  ansible.builtin.command: gup update
  changed_when: false

- name: Update Rust toolchain
  ansible.builtin.command: rustup update
  changed_when: false

- name: Update Krew packages
  ansible.builtin.command: kubectl-krew upgrade
  changed_when: false

- name: Update Python packages
  ansible.builtin.command: uv tool upgrade --all
  changed_when: false

- name: Update mise packages
  ansible.builtin.command: mise upgrade --bump
  changed_when: false

- name: Prune Docker components
  ansible.builtin.shell: |
    set -e
    docker image prune -a -f
    docker volume prune -a -f
    docker network prune -f
  changed_when: false
