---
- name: Update Homebrew-related components
  block:
    - name: Update Homebrew & Homebrew packages
      community.general.homebrew:
        path: /home/linuxbrew/.linuxbrew/bin
        update_homebrew: true
        upgrade_all: true
    - name: Run brew autoremove
      ansible.builtin.command: /home/linuxbrew/.linuxbrew/bin/brew autoremove
      changed_when: false

- name: Update Go packages
  ansible.builtin.shell: |
    export PATH=$PATH:/usr/local/go/bin
    /home/{{ ansible_user }}/go/bin/gup update
  changed_when: false

- name: Update Rust
  ansible.builtin.command: /home/linuxbrew/.linuxbrew/bin/rustup update
  changed_when: false

- name: Update Krew packages
  ansible.builtin.command: /home/linuxbrew/.linuxbrew/bin/kubectl-krew upgrade
  changed_when: false

- name: Update Python packages
  ansible.builtin.command: /home/linuxbrew/.linuxbrew/bin/uv tool upgrade --all
  changed_when: false

- name: Update mise packages
  ansible.builtin.command: /home/linuxbrew/.linuxbrew/bin/mise upgrade --bump
  changed_when: false

- name: Prune Docker components
  ansible.builtin.shell: |
    docker image prune -a -f
    docker volume prune -a -f
    docker network prune -f
  changed_when: false
