- name: Copy Updater Service Template
  become: true
  ansible.builtin.template:
    src: updater.service.j2
    dest: /etc/systemd/system/updater.service
    mode: "0644"
- name: Enable Updater Service
  become: true
  ansible.builtin.systemd:
    name: updater.service
    enabled: true
    daemon_reload: true
    state: restarted
