- name: Copy Git Config
  ansible.builtin.copy:
    src: gitconfig
    dest: ~/.gitconfig
    mode: "0664"

- name: Update dotfiles
  block:
    - name: Get Current Dir Path
      ansible.builtin.command: pwd
      register: git_dotfiles_dir
      changed_when: false
    - name: Update dotfiles
      ansible.builtin.git: # noqa: latest
        repo: https://github.com/logica0419/dotfiles.git
        dest: "{{ git_dotfiles_dir.stdout }}"
      failed_when: false
