---
- name: Setup default shell
  block:
    - name: Install Homebrew bash
      community.general.homebrew:
        name: bash
        state: present
    - name: Change default shell to Homebrew bash
      become: true
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        shell: "{{ check_os_brew_base_path }}/bin/bash"
    - name: Remove zsh related files
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop: "{{ query('ansible.builtin.fileglob', ansible_facts['user_dir'] + '/.zsh*') }}"

- name: SSH settings
  block:
    - name: Create .ssh directory
      ansible.builtin.file:
        path: "{{ ansible_facts['user_dir'] }}/.ssh"
        state: directory
        mode: "0755"
    - name: Move SSH config
      ansible.builtin.copy:
        src: ssh_config
        dest: "{{ ansible_facts['user_dir'] }}/.ssh/config"
        mode: "0644"

- name: Show hidden files in Finder
  community.general.osx_defaults:
    domain: com.apple.finder
    key: AppleShowAllFiles
    type: bool
    value: true
  notify: Restart Finder

- name: Install cask applications
  community.general.homebrew_cask:
    name:
      # 必須アプリケーション
      - bitwarden
      - logitech-g-hub
      - microsoft-office
      - google-chrome
      - tailscale-app

      # エンジニアリング系
      - visual-studio-code
      - devtoys
      - kicad

      # 音楽系
      - freac
      - musescore
      - rekordbox
      - waves-central

      # 画像・映像系
      - adobe-creative-cloud
      - figma
      - obs
      - xnconvert

      # SNS・通信系
      - discord
      - mattermost
      - signal
      - slack
      - zoom

      # ゲーム系
      - steam
    state: present

- name: Setup updater
  block:
    - name: Get current dir path
      ansible.builtin.command: pwd
      register: mac_dotfiles_dir
      changed_when: false
    - name: Get ansible-playbook path
      ansible.builtin.command: which ansible-playbook
      register: mac_ansible_playbook_path
      changed_when: false
    - name: Create launch agents directory
      ansible.builtin.file:
        path: "{{ ansible_facts['user_dir'] }}/Library/LaunchAgents"
        state: directory
        mode: "0755"
    - name: Create updater log directory
      ansible.builtin.file:
        path: "{{ ansible_facts['user_dir'] }}/.local/state/dotfiles"
        state: directory
        mode: "0755"
    - name: Copy updater launchd plist
      ansible.builtin.template:
        src: updater.plist.j2
        dest: "{{ ansible_facts['user_dir'] }}/Library/LaunchAgents/com.dotfiles-updater.plist"
        mode: "0644"
      register: mac_updater_plist
    - name: Check updater launch agent status
      ansible.builtin.command: >-
        launchctl print gui/{{ ansible_facts['user_uid'] }}/com.dotfiles-updater
      register: mac_updater_status
      failed_when: false
      changed_when: false
    - name: Unload updater launch agent
      ansible.builtin.command: >-
        launchctl bootout gui/{{ ansible_facts['user_uid'] }}
        {{ ansible_facts['user_dir'] }}/Library/LaunchAgents/com.dotfiles-updater.plist
      when: mac_updater_plist is changed or mac_updater_status.rc == 0
      failed_when: false
      changed_when: mac_updater_status.rc == 0
    - name: Load updater launch agent
      ansible.builtin.command: >-
        launchctl bootstrap gui/{{ ansible_facts['user_uid'] }}
        {{ ansible_facts['user_dir'] }}/Library/LaunchAgents/com.dotfiles-updater.plist
      when: mac_updater_plist is changed or mac_updater_status.rc != 0
      changed_when: true
    - name: Enable updater launch agent
      ansible.builtin.command: >-
        launchctl enable gui/{{ ansible_facts['user_uid'] }}/com.dotfiles-updater
      changed_when: false
