---
- name: Install Homebrew
  install_brew:

- name: Update Homebrew
  community.general.homebrew:
    update_homebrew: true

- name: Install packages
  block:
    - name: Register Homebrew tap
      community.general.homebrew_tap:
        name:
          - ycd/tap
          - k1LoW/tap
          - hashicorp/tap
          - oven-sh/bun
    - name: Install packages
      community.general.homebrew:
        state: latest
        name:
          - rustup
          - uv
          - git
          - gh
          - htop
          - shfmt
          - hashicorp/tap/terraform
          - tflint
          - direnv
          - dstp
          - tbls
          - hadolint
          - go-task
          - just
          - mise
          - oven-sh/bun/bun
          - oxlint
          - oxfmt
          - stylelint
