---
- name: Install Homebrew
  install_brew:

- name: Update Homebrew
  community.general.homebrew:
    update_homebrew: true

- name: Install Homebrew packages
  block:
    - name: Register Homebrew tap
      community.general.homebrew_tap:
        name:
          - ycd/tap
          - k1LoW/tap
          - hashicorp/tap
          - terraform-linters/tap
          - oven-sh/bun
          - tinygo-org/tools
          - terror/tap
    - name: Trust Homebrew tap
      ansible.builtin.command: brew trust {{ item }}
      changed_when: false
      loop:
        - tinygo-org/tools/tinygo
        - terror/tap/just-lsp
        - hashicorp/tap/terraform
        - terraform-linters/tap/tflint
        - oven-sh/bun/bun
        - k1low/tap/tbls
        - ycd/tap/dstp
    - name: Install Homebrew packages
      community.general.homebrew:
        name:
          - rustup
          - uv
          - cmake
          - ninja
          - llvm
          - tinygo-org/tools/tinygo
          - git
          - gh
          - htop
          - jq
          - yq
          - shfmt
          - hashicorp/tap/terraform
          - terraform-linters/tap/tflint
          - direnv
          - ycd/tap/dstp
          - k1low/tap/tbls
          - hadolint
          - go-task
          - just
          - just-lsp
          - mise
          - oven-sh/bun/bun
          - oxlint
          - oxfmt
          - stylelint
          - easyeda2kicad
        state: present
