---
- name: Deploy gitconfig file
  ansible.builtin.template:
    src: gitconfig.j2
    dest: "{{ ansible_facts.user_dir }}/.gitconfig"
    mode: "0664"

- name: Generate SSH allowed signers file
  when: not git_sdplane
  block:
    - name: Create SSH directory
      ansible.builtin.file:
        path: "{{ ansible_facts.user_dir }}/.ssh"
        state: directory
        mode: "0700"
    - name: Get SSH signing key status
      ansible.builtin.stat:
        path: "{{ ansible_facts.user_dir }}/.ssh/id_ed25519.pub"
      register: git_signing_key_stat
    - name: Generate allowed signers from signing key
      when: git_signing_key_stat.stat.exists
      block:
        - name: Read SSH signing key
          ansible.builtin.slurp:
            src: "{{ ansible_facts.user_dir }}/.ssh/id_ed25519.pub"
          register: git_signing_key_slurp
        - name: Generate allowed signers entry
          ansible.builtin.set_fact:
            git_allowed_signers_entry: |
              {{ git_user_email }} {{ git_signing_key_fields[0] }} {{ git_signing_key_fields[1] }}
          vars:
            git_signing_key_fields: "{{ (git_signing_key_slurp.content | b64decode).split() }}"
        - name: Deploy allowed signers file
          ansible.builtin.copy:
            dest: "{{ ansible_facts.user_dir }}/.ssh/allowed_signers"
            mode: "0600"
            content: "{{ git_allowed_signers_entry }}"

- name: Configure Go repository credentials
  when: not git_sdplane
  block:
    - name: Get .gitcookies status
      ansible.builtin.stat:
        path: "{{ ansible_facts.user_dir }}/.gitcookies"
      register: git_stat_result
    - name: Create empty .gitcookies
      ansible.builtin.file:
        path: "{{ ansible_facts.user_dir }}/.gitcookies"
        state: touch
        mode: "0664"
      when: not git_stat_result.stat.exists
    - name: Stop playbook for credential setup
      ansible.builtin.fail:
        msg: Please setup credentials for Go Git repositories
      when: not git_stat_result.stat.exists or git_stat_result.stat.size == 0
