- name: Get Current Dir Path
  ansible.builtin.command: pwd
  register: updater_server_dotfiles_dir
  changed_when: false
- name: Get ansible-playbook Path
  ansible.builtin.command: which ansible-playbook
  register: updater_server_ansible_playbook_path
  changed_when: false
- name: Setup Updater for Server
  ansible.builtin.cron:
    name: update packages
    minute: 0
    hour: 4
    job: >-
      {{ updater_server_ansible_playbook_path.stdout }} -v -u {{ ansible_user }}
      -i {{ updater_server_dotfiles_dir.stdout }}/inventory {{ updater_server_dotfiles_dir.stdout }}/update.yaml

- name: Get reboot Path
  ansible.builtin.command: which reboot
  register: updater_server_reboot_path
  changed_when: false
- name: Setup Periodical reboot for Server
  become: true
  ansible.builtin.cron:
    name: reboot server
    minute: 30
    hour: 4
    user: root
    job: "[ -e /var/run/reboot-required ] && {{ updater_server_reboot_path.stdout }} 0"
