---
- name: Install gnu-tar
  community.general.homebrew:
    name: gnu-tar
    state: present

- name: Download latest Go (Darwin)
  become: true
  ansible.builtin.unarchive:
    src: https://go.dev/dl/{{ go_latest.stdout }}.darwin-arm64.tar.gz
    dest: /usr/local
    remote_src: true
    tar: "{{ check_os_brew_base_path }}/bin/gtar"
