---
- name: Install GNU tar package
  community.general.homebrew:
    name: gnu-tar
    state: present

- name: Install latest Go package (Darwin)
  become: true
  ansible.builtin.unarchive:
    src: https://go.dev/dl/{{ go_latest.stdout }}.darwin-arm64.tar.gz
    dest: /usr/local
    remote_src: true
