version: "3"

services:
  mariadb:
    container_name: local-db_mariadb
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  phpmyadmin:
    container_name: local-db_phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
      - PMA_USER=root
      - PMA_PASSWORD=password
    ports:
      - 3307:80
    depends_on:
      - mariadb

volumes:
  db: null
