services:
  mysql:
    container_name: local-db_mysql
    image: mysql:9.5.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
      - 33060:33060
    volumes:
      - db:/var/lib/mysql

  phpmyadmin:
    container_name: local-db_phpmyadmin
    image: phpmyadmin:5.2.3-fpm-alpine
    restart: always
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=password
    ports:
      - 3307:80
    depends_on:
      - mysql

volumes:
  db: null
