---
- name: Install Colima
  community.general.homebrew:
    name: colima
    state: present

- name: Start Colima
  community.general.homebrew_services:
    name: colima
    state: present

- name: Switch Docker context to Colima
  ansible.builtin.command: docker context use colima
  changed_when: false
