---
- name: Configure Docker engine
  become: true
  block:
    - name: Configure Docker repository
      ansible.builtin.deb822_repository:
        name: docker
        types: deb
        uris: https://download.docker.com/linux/ubuntu
        suites: jammy
        components: stable
        signed_by: https://download.docker.com/linux/debian/gpg
        state: present
      register: docker_repo
      notify: Update apt cache
    - name: Flush handlers
      ansible.builtin.meta: flush_handlers
    - name: Install Docker engine
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
    - name: Deploy Docker daemon config
      ansible.builtin.copy:
        src: daemon.json
        dest: /etc/docker/daemon.json
        mode: "0644"
      notify: Restart Docker

- name: Configure docker group
  become: true
  block:
    - name: Create docker group
      ansible.builtin.group:
        name: docker
        state: present
    - name: Append current user to docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups:
          - docker
        append: true
      register: docker_result
    - name: Stop playbook for group refresh
      ansible.builtin.fail:
        msg: Please restart the computer to apply docker group privilege
      when: docker_result is changed # noqa: no-handler
