---
- name: Setup Docker cli
  block:
    - name: Install Docker cli and plugins
      community.general.homebrew:
        name:
          - docker
          - docker-compose
          - docker-buildx
        state: present
    - name: Create Docker config directory
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/.docker"
        state: directory
        mode: "0755"
    - name: Configure Docker CLI plugins directory
      ansible.builtin.template:
        src: config.json.j2
        dest: "{{ ansible_user_dir }}/.docker/config.json"
        mode: "0644"

- name: Include OS-specific Docker installation
  ansible.builtin.include_tasks: "{{ ansible_facts['system'] | lower }}.yaml"
