---
- name: Install Docker CLI and plugins
  community.general.homebrew:
    name:
      - docker
      - docker-compose
      - docker-buildx
    state: present

- name: Configure Docker config
  block:
    - name: Create Docker config directory
      ansible.builtin.file:
        path: "{{ ansible_facts.user_dir }}/.docker"
        state: directory
        mode: "0755"
    - name: Deploy Docker config file
      ansible.builtin.template:
        src: "config-{{ ansible_facts.system | lower }}.json.j2"
        dest: "{{ ansible_facts.user_dir }}/.docker/config.json"
        mode: "0644"

- name: Include OS-specific Docker installation
  ansible.builtin.include_tasks: "{{ ansible_facts.system | lower }}.yaml"
