- name: Set gpg-agent Config
  ansible.builtin.template:
    src: gpg-agent.conf.j2
    dest: ~/.gnupg/gpg-agent.conf
    mode: 0644
  notify: Stop gpg-agent
  register: result

- name: Install gpg-agent
  become: true
  ansible.builtin.apt:
    update_cache: true
    name:
      - gpg-agent
    state: present

- name: Flush Handlers
  ansible.builtin.meta: flush_handlers
- name: Stop Ansible Playbook
  ansible.builtin.fail:
    msg: Please run the playbook again after reloading .bashrc
  when: result.changed # noqa: no-handler
