- name: Restart Local DB
  ansible.builtin.shell: docker compose down && docker compose up -d
  environment:
    COMPOSE_PROJECT_NAME: local_db
    COMPOSE_FILE: "{{ update_dotfiles_dir.stdout }}/roles/db/files/docker-compose.yaml"
  changed_when: false
  failed_when: false
