- name: Create .hushlogin
  ansible.builtin.file:
    path: ~/.hushlogin
    state: touch
    access_time: preserve
    modification_time: preserve
    mode: "0644"

- name: Copy .colorrc to home directory
  ansible.builtin.copy:
    src: .colorrc
    dest: ~/.colorrc
    mode: "0644"

- name: Copy .bashrc to home directory
  ansible.builtin.copy:
    src: .bashrc
    dest: ~/.bashrc
    mode: "0644"
  register: rc_result
- name: Stop Ansible Playbook
  ansible.builtin.fail:
    msg: Please run the playbook again after reloading .bashrc
  when: rc_result.changed # noqa: no-handler
