---
- name: Create .hushlogin file
  ansible.builtin.file:
    path: "{{ ansible_facts.user_dir }}/.hushlogin"
    state: touch
    access_time: preserve
    modification_time: preserve
    mode: "0644"

- name: Configure environment files
  block:
    - name: Create config directories
      ansible.builtin.file:
        path: "{{ ansible_facts.user_dir }}/{{ item }}"
        state: directory
        mode: "0700"
      loop:
        - .config
        - .config/environment.d
    - name: Deploy shared environment file
      ansible.builtin.template:
        src: env.conf.j2
        dest: "{{ ansible_facts.user_dir }}/.config/environment.d/env.conf"
        mode: "0600"
      register: rc_env_file_result

- name: Configure rc files for root
  become: true
  when: ansible_facts.system == "Linux"
  block:
    - name: Deploy .bashrc to root home
      ansible.builtin.copy:
        src: bashrc-root
        dest: /root/.bashrc
        mode: "0644"
    - name: Deploy .profile to root home
      become: true
      ansible.builtin.template:
        src: profile.j2
        dest: /root/.profile
        mode: "0644"

- name: Configure rc files for current user
  block:
    - name: Deploy .bashrc to home directory
      ansible.builtin.copy:
        src: bashrc
        dest: "{{ ansible_facts.user_dir }}/.bashrc"
        mode: "0644"
      register: rc_bashrc_result
    - name: Deploy .profile to home directory
      ansible.builtin.template:
        src: profile.j2
        dest: "{{ ansible_facts.user_dir }}/.profile"
        mode: "0644"
      register: rc_profile_result
    - name: Stop playbook for shell reload
      ansible.builtin.fail:
        msg: Please run the playbook again after reloading .bashrc or .profile
      when: rc_env_file_result is changed or rc_bashrc_result is changed or rc_profile_result is changed
