---
- name: Create .hushlogin
  ansible.builtin.file:
    path: "{{ ansible_facts.user_dir }}/.hushlogin"
    state: touch
    access_time: preserve
    modification_time: preserve
    mode: "0644"

- name: Setup rc files for root
  become: true
  when: ansible_facts.system == "Linux"
  block:
    - name: Copy .bashrc to root home directory
      ansible.builtin.copy:
        src: bashrc-root
        dest: /root/.bashrc
        mode: "0644"
    - name: Copy .profile to root home directory
      become: true
      ansible.builtin.template:
        src: profile.j2
        dest: /root/.profile
        mode: "0644"

- name: Setup rc files for current user
  block:
    - name: Create environment.d directory
      ansible.builtin.file:
        path: "{{ ansible_facts.user_dir }}/.config/environment.d"
        state: directory
        mode: "0755"
    - name: Copy shared environment file
      ansible.builtin.template:
        src: env.conf.j2
        dest: "{{ ansible_facts.user_dir }}/.config/environment.d/env.conf"
        mode: "0644"
      register: rc_env_file_result
    - name: Copy .bashrc to home directory
      ansible.builtin.copy:
        src: bashrc
        dest: "{{ ansible_facts.user_dir }}/.bashrc"
        mode: "0644"
      register: rc_bashrc_result
    - name: Copy .profile to home directory
      ansible.builtin.template:
        src: profile.j2
        dest: "{{ ansible_facts.user_dir }}/.profile"
        mode: "0644"
      register: rc_profile_result
    - name: Stop ansible-playbook
      ansible.builtin.fail:
        msg: Please run the playbook again after reloading .bashrc or .profile
      when: rc_env_file_result is changed or rc_bashrc_result is changed or rc_profile_result is changed
